readr-media/react

- packages/qa-list/Makefile
- packages/qa-list/dev/entry.js
- packages/qa-list/dev/index.html
- packages/qa-list/dev/webpack.config.js
- packages/qa-list/package.json
- packages/qa-list/src/build-code/client.js
- packages/qa-list/src/build-code/constants.js
- packages/qa-list/src/build-code/index.js
- packages/qa-list/src/index.js
- packages/qa-list/src/react-components/draft/block-redender-fn.js
- packages/qa-list/src/react-components/draft/color-text.js
- packages/qa-list/src/react-components/draft/embedded-code.js
- packages/qa-list/src/react-components/draft/entity-decorator.js
- packages/qa-list/src/react-components/draft/image.js
- packages/qa-list/src/react-components/index.js
- packages/qa-list/src/react-components/layout/section.js
- packages/qa-list/src/react-components/list/qa-card.js
- packages/qa-list/src/react-components/list/qa-list.js
- packages/qa-list/webpack.config.js
將 `qa-list` 獨立拆出來作為一個 package。
詳細實作和 demo 可參考：https://github.com/readr-media/react/pull/14
> chore(qa-list): add qa-list package

- packages/qa/src/react-components/draft/block-redender-fn.js
- packages/qa/src/react-components/draft/color-text.js
- packages/qa/src/react-components/draft/embedded-code.js
- packages/qa/src/react-components/draft/entity-decorator.js
- packages/qa/src/react-components/draft/image.js
- packages/qa/src/react-components/form/result.js
原本是 https://github.com/readr-media/react/pull/10 ，但因 branch 失效故重發。
> refactor(qa): add result component

- packages/qa/dev/mock-data.js
- packages/qa/src/react-components/form/result.js
> refactor(qa): update mock data of answers updatedAt

- packages/feedback/src/react-components/hooks/use-comments.js
基於以下後端的原因，有可能在拿取comment的時候會拿到重複的comment，需另外過濾不要把重複的comment render出來
由於 keystone schema 和 resolver 沒有支援 cursor-based pagination，
在使用 skip ( 起始 index ) + take ( 取得數量 ) 的情況下，
在每個 query pagination 資料間，如果有新的資料加入，
會導致 query 出來的資料和前一次是沒辦法完美連接。
例如：
目前資料長這樣子`[1, 2, 3, 4, 5, 6, 7, 8, 9]`
當query用數字大到小，使用 skip: 0, take: 3 參數時，
取得`[9, 8, 7]`
接著，增加了 10 在尾端，使得資料變成`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`
第二次 query 時，使用上次回傳的 index 資訊，使用 skip: 3, take: 3 參數，
取得`[7, 6, 5]`
和第一次的結果有重複的成員
> fix(feedback): prevent render same comment twice

- packages/questionnaire/dev/index.html
- packages/questionnaire/src/react-components/index.js
- packages/questionnaire/src/react-components/layout/default-layout.js
> refactor(questionnaire): add default layout and render it

- .eslintrc.json
- babel.config.js
- package.json
- packages/election-votes-comparison/package.json
- packages/election-votes-comparison/src/data-loaders/index.js
- packages/election-votes-comparison/src/index.js
- yarn.lock
- add `src/data-loaders/index.js`
- update pkg default export. Export `ReactComponent` and `DataLoader`
創造 `DataLoader` instance 時，需要提供 `year`, `type` 和 `area` 三個參數，
關於參數的值，請參考[程式碼](https://github.com/nickhsine/readr-react/blob/0a672013e99a7351251e1359c4ae726ffe423bce/packages/election-votes-comparison/src/data-loaders/index.js#L175-L214)。
因為庭葳還在處理資料，可以先用
```
const year='2018'
const type='councilMember'
const area='allDistricts'
```
去測。但因為是所有縣市的資料混在一起，所以傳給 `ReactComponent` 時，要改成
```
<EVCComponent
year={2018}
title="臺北市議員選舉"
districts={data.TaipeiCity.districts}
>
```
註：
`TaipeiCity` 是大寫開頭，這個之後會改成 `taipeiCity`。
```
import EVC from '@readr-media/react-election-votes-comparison'
const DataLoader = EVC.DataLoader
const EVCComponent = EVC.ReactComponent
async function load() {
const dataLoader …
```
> feat(evc): add data-loaders

- packages/election-votes-comparison/src/react-components/index.js
- packages/election-votes-comparison/src/react-components/list.js
- packages/election-votes-comparison/src/react-components/theme.js
[e03f296](https://github.com/readr-media/react/pull/85/commits/e03f296a42019ad3138a68f94432cdda34ace109): 更新`theme.js`，新增屬性`mnewsElection2022`。在`mnewsElection2022中，除了調整既有的key的value以外，更新增了兩個property：`container`、`table.candidate.name`，用於更改列表的顏色、以及候選人名字的顏色。
[780e5b1](https://github.com/readr-media/react/pull/85/commits/780e5b12ba429dfe4236506a8f4ccdaee0fc57fd)：更新元件`index.js`與`list.js`，使其符合設計稿，改動如下
- [當`props.theme`為`mnewsElection2022`時，隱藏`index.js`中的`Header`](https://github.com/readr-media/react/pull/85/commits/780e5b12ba429dfe4236506a8f4ccdaee0fc57fd#diff-45f32d6ccafbe4a7cc10498ba810f8b92c20d08c78eca8ddcf0de12dd091ae0bR463)
- [將`index.js`的`props.theme`傳入元件`List`](https://github.com/readr-media/react/pull/85/commits/780e5b12ba429dfe4236506a8f4ccdaee0fc57fd#diff-45f32d6ccafbe4a7cc10498ba810f8b …
> style(evc): update theme and add property `mnewsElection2022`, adjust stylesheet

- packages/feedback/CHANGELOG.md
- packages/feedback/package.json
- packages/feedback/src/react-components/contexts/form-context.js
- packages/feedback/src/react-components/contexts/use-form.js
- packages/feedback/src/react-components/form/thumbs-form/thumb-field.js
- packages/feedback/src/react-components/hooks/use-thumbsUp.js
- packages/feedback/src/react-components/hooks/use-user.js
- packages/feedback/src/react-components/index.js
* fix: `giveLikes` is callable after userId is ready
* feat: add `storageKey` option to set sessionStorage key
* feat: prevent manipulate likes before data loaded
* feat: add disabled style of thumb buttons
> chore(feedback): bump version to 3.1.0

- packages/election-widgets/package.json
- packages/election-widgets/src/seat-chart/react-components/index.js
refactor(election-widgets): update party colors
> chore(election-widgets): bump version to 1.0.6

- packages/live-blog/package.json
- packages/live-blog/src/react-components/live-blog-container.js
- packages/live-blog/src/react-components/live-blog-tag.js
refactor(live-blog): tag button show whole tag names
> refactor(live-blog): bump version to 1.1.4

- packages/embed-code-generator/package.json
- packages/embed-code-generator/src/build-code/index.js
- packages/full-screen-video/CHANGELOG.md
- packages/full-screen-video/package.json
- yarn.lock
- 更新 package `full-screen-video` 版號。
- 在 embed-code-generator 新增 full-screen-video embed 部分。
> feat(embed-code-generator): build full-screen-video embed

- packages/embed-code-generator/package.json
- packages/embed-code-generator/src/build-code/client.js
- packages/embed-code-generator/src/build-code/index.js
- packages/embed-code-generator/yarn.lock
- 新增 `@readr-media/text-selector`
> feat(ecg): add @readr-media/text-selector

- packages/embed-code-generator/README.md
- packages/embed-code-generator/src/build-code/client.js
- packages/embed-code-generator/src/build-code/index.js
- packages/embed-code-generator/webpack.config.js
當一個頁面有多個（兩個以上）不同版本的 ecg 產生的 embed code 時，會出現異常狀態。
原因在於 embed code 沒有根據版號區分 bundles，當 bundles 有依賴關係時，新的版號的 bundle 可能拿到舊的版本的 bundle，導致 embed code 在某些情況下會無法正常顯示。
將 ecg 的版號加入 embed code 中做判斷，才會拿到正確的資料和依賴的 bundles。
> fix(ecg): different version causes abnormal rendering

- packages/image/CHANGELOG.md
- packages/image/README.md
- packages/image/dev/entry.js
- packages/image/package.json
- packages/image/src/react-components/index.js
1. 新增一參數 `intersectionObserverOptions`，用於調整圖片懶載入的觸發條件
> feat(image): add param intersectionObserverOptions

- packages/embed-code-generator/dev/mocks/theatre/index.js
- packages/embed-code-generator/package.json
- packages/embed-code-generator/yarn.lock
- 更新 `embed-code-generator` 所使用的 `react-theatre` 版本。
- 更新 `react-theatre` 的 mock dev data。
- `embed-code-generator` 版本升至 `2.4.0-alpha.4`。
> chore(ecg): update `react-theatre` version

- packages/embed-code-generator/package.json
- packages/embed-code-generator/yarn.lock
- packages/theatre/dev/index.html
- packages/theatre/package.json
- packages/theatre/src/react-components/components/demo-scroll.js
- packages/theatre/src/react-components/components/demo-video.js
- `embed-code-generator` 版本升至 `2.4.0-alpha.16`
- `theatre` 版本升至 `0.2.0-alpha.4`
> chore(ecg): bump up `embed-code-generator` version

- packages/embed-code-generator/src/build-code/client.js
- hydrate and render will loop through multiple data for the same type of embed code
> refactor(ecg): render multiple embed code for each type

- packages/embed-code-generator/package.json
- packages/embed-code-generator/yarn.lock
- packages/theatre/dev/entry.js
- packages/theatre/package.json
- packages/theatre/src/react-components/constants/background.js
- packages/theatre/src/react-components/constants/font.js
- packages/theatre/src/react-components/constants/image.js
- packages/theatre/src/react-components/constants/video.js
- `react-theatre`：更新元件 font/image/bg/video 參數設定，版本升至 `0.2.0-alpha.7`。
- `embed-code-generator`：更新 `theatre` 版本，版本升至 `2.4.0-alpha.20`。
> feat(theatre): update element constants

- packages/feedback/CHANGELOG.md
- packages/feedback/package.json
- packages/feedback/src/react-components/form/single-option-form/single-option-field.js
- packages/feedback/src/typedef.js
> fix(feedback): collaboration issues

- packages/dropping-text/package.json
- packages/dropping-text/src/react-components/index.js
- packages/embed-code-generator/package.json
- packages/embed-code-generator/yarn.lock
- 套件 `dropping-text` 背景新增為 `#ffffff`，版本升至 `1.0.7`。
- 更新 `embed-code-generator` 內 `dropping-text` 版本，並將版本升至 `2.4.3-alpha.2`。
> feat(dropping-text): add background color

- packages/image/CHANGELOG.md
- packages/image/package.json
- packages/image/src/react-components/index.js
1. 使用 useState 儲存圖片狀態，包含載入的圖片、是否載入等
> refactor(image): use useState to store image status

- packages/feedback/CHANGELOG.md
- packages/feedback/package.json
- packages/feedback/src/react-components/form/comments/comment-item.js
- packages/feedback/src/react-components/form/form.js
- fix: add missing key attribute
- refactor: make commentItem cropping behavior configurable
- fix: remove unwanted form submission behavior
> chore(feedback): bump version to 3.7.0

- packages/feedback/CHANGELOG.md
- packages/feedback/dev/mock-forms.js
- packages/feedback/package.json
- packages/feedback/src/react-components/form/comment-form/comment-field.js
- packages/feedback/src/react-components/form/comments/comments.js
- packages/feedback/src/react-components/hooks/use-comments.js
- packages/feedback/src/typedef.js
* Fix behavior under strict mode
* Add defaultText config to text field
> feat(feedback): bump version to 3.8.0

- packages/feedback/CHANGELOG.md
- packages/feedback/package.json
- packages/feedback/src/react-components/hooks/use-user.js
* replace sessionStorage with localStorage
> feat(feedback): bump version to 4.0.0

- packages/election-widgets/package.json
- packages/election-widgets/src/seat-chart/data-loader.js
- packages/election-widgets/src/votes-comparison/data-loader.js
- [fix(election-map): lack of break in switch syntax](https://github.com/readr-media/react/commit/bba0deea021f64c1606bab1bbfb6d0bc6efdeaea)
- [refactor(election-map): fetch legislator seat data](https://github.com/readr-media/react/commit/6787dc7d6524c39994abc414a91843c5f79da5dd)
> refactor(election-map): modify election map

- packages/theatre/dev/entry.js
- packages/theatre/package.json
- packages/theatre/src/react-components/components/stage.js
- packages/theatre/src/react-components/constants/bgVideo.js
- packages/theatre/src/react-components/constants/index.js
- packages/theatre/src/react-components/elements/bgVideo.js
- 新增 `bgVideo` 捲動式影片元件。
- 新增 `bgVideo` 預設值參數。
- 更新 entry demo JSON 範例。
- 版本更新至 `1.4.0-alpha.1`。
> feat(theatre): add background-scrollable-video elements

- packages/embed-code-generator/package.json
- packages/embed-code-generator/yarn.lock
- packages/theatre/package.json
- packages/theatre/src/react-components/components/demo-scroll.js
- packages/theatre/src/react-components/components/stage.js
- packages/theatre/src/react-components/constants/bgVideo.js
- packages/theatre/src/react-components/constants/video.js
- packages/theatre/src/react-components/elements/bgVideo.js
- packages/theatre/src/react-components/elements/video.js
- `bgVideo` 元件新增：opacity、speed 調整參數。
- `video` 元件新增：opacity 調整參數。
- 調整「載入中」判斷：需 bgVideo/video/image 元件 loading 完成 ＆ bgVideo buffer 至少載入 1/4 時，才顯示內容。
- 調整 loading / error handle 設定。
- 版本升至 `1.4.0-alpha.3`。
- 版本升至 `2.4.3-alpha.20`。
> fix(theatre): modify loading setting & bgVideo/video configs

- packages/election-widgets/dev/entry.js
- packages/election-widgets/src/votes-comparison/data-loader.js
- packages/election-widgets/src/votes-comparison/react-components/index.js
- packages/election-widgets/src/votes-comparison/react-components/manager.js
* \[[`7d67d04988`](https://github.com/nodejs/node/commit/7d67d04988)] - **feat(election-widgets)**: add legislator-recall condition (LinHeMa)
* \[[`79e37b6491`](https://github.com/nodejs/node/commit/79e37b6491)] - **feat(election-widgets)**: add recall condition (LinHeMa)
> feat: add recall type to election widgets
